const images = {
  hamburger: require("./images/hamburger.png"),
  nikkei: require("./images/nikkei.png"),
  pizzas: require("./images/pizzas.png"),
  dish1: require("./images/dish1.png"),
  dish2: require("./images/dish2.png"),
  dish3: require("./images/dish3.png"),
  chef1: require("./images/chef1.jpg"),
  chef2: require("./images/chef2.jpg"),
  iconShipping: require("./images/iconShipping.png"),
  home: require("./images/iconHome.png"),
  chef: require("./images/iconChef.png"),
  search: require("./images/iconSearch.png"),
  more: require("./images/iconMore.png"),
  homeActive: require("./images/iconHomeActive.png"),
  chefActive: require("./images/iconChefActive.png"),
  seachActive: require("./images/iconSearchActive.png"),
  location: require("./images/iconLocation.svg"),
  caretDown: require("./images/iconCaretDown.svg"),
  close: require("./images/iconClose.png"),
  step1: require("./images/step1.png"),
  step2: require("./images/step2.png"),
  step3: require("./images/step3.png"),
  start: require("./images/iconStart.svg"),
  startActive: require("./images/iconStartActive.svg"),
  next: require("./images/iconNext.png"),
  previous: require("./images/iconBack.png"),
  minus: require("./images/iconMinus.png"),
  add: require("./images/iconAdd.png"),
  cart: require("./images/iconCart.svg"),
  check: require("./images/iconCheck.svg"),
  checkTiny: require("./images/iconCheckTiny.svg"),
  heart: require("./images/iconHeart.svg"),
  caretRight: require("./images/iconCaretRight.svg"),
  card: require("./images/cardPaymentMethod.png"),
}

export default images
